### ISSUE TITLE
@tlhszc 应该是访问网站超时导致的问题。爬虫未给出自定义超时选项，默认5秒超时，解决方案：

### ISSUE THREAD

**Issue by tlhszc** [H4ckForJob/dirmap#13]
@tlhszc 应该是访问网站超时导致的问题。爬虫未给出自定义超时选项，默认5秒超时，解决方案：

```python
#找到dirmap\lib\controller\bruter.py文件，修改第348行timeout超时参数值为30秒。
#response = requests.get(conf.url, headers=headers, timeout=5)
response = requests.get(conf.url, headers=headers, timeout=30)
```

使用你提供的这个网站<http://testphp.vulnweb.com>，测试爬虫模式，但在output文件夹内仍然没有发现文件输出

**Comment by H4ckForJob** [comment]
@tlhszc 您的情景是，`[爬虫模式]`未扫描出目录文件泄露。因为扫描到才会生成结果文件，所以`output`文件夹内无结果文件。您可以测试下使用`[字典模式]`或其他模式进行测试，观察是否能生成结果文件。
