### ISSUE TITLE
对http://ip:port的网站扫描结果无法生成*.txt

### ISSUE THREAD

**Issue by tysmlq** [H4ckForJob/dirmap#15]
测试了几个IP：端口的url，如http://1.1.1.1:8080 虽然能扫描完成，cmd下看到结果，但out目录生成0字节的1.1.1.1文件，且不是txt后缀，与直接扫描ip不一样。

**Comment by H4ckForJob** [comment]
@tysmlq hello，window下文件名不能存在`:`，现在已将文件名中的`:`替换成`_`。
