### ISSUE TITLE
Require English Document Support

### ISSUE THREAD

**Issue by Teicu** [H4ckForJob/dirmap#23]
Hi 

can u add a wiki in english please? Or maybe just a readme if u can. 

Also is there a way to update or we have to reinstall a fresh release? 

Thanks

**Comment by ttttmr** [comment]
The `help` information and `dirmap.conf` are in English, I will write an English version of the readme as soon as possible.
For updates, it is recommended to use `git clone` to download, you can use `git pull` update program

**Comment by Teicu** [comment]
Awesome. Thank you very much for help and for this awesome tool.
 
Regards

**Comment by Teicu** [comment]
`dirmap Pentest$ sudo git pull update dirmap
Password:
fatal: 'update' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
