### ISSUE TITLE
总是显示无法识别域名

### ISSUE THREAD

**Issue by yu4hao4** [H4ckForJob/dirmap#26]
dirmap.py: error: unrecognized arguments: https://baidu.com
dirmap.py: error: unrecognized arguments: https://askubuntu.com/

**Comment by m01e-40x** [comment]
mac下确实有这个问题：
![image](https://user-images.githubusercontent.com/11158624/60752844-35d1e080-9ffd-11e9-96db-7f4e6998cf17.png)

**Comment by m01e-40x** [comment]
> dirmap.py: error: unrecognized arguments: https://baidu.com
> dirmap.py: error: unrecognized arguments: https://askubuntu.com/

找到原因了，去掉 -i 后面的 U 就行了，看了下代码，U根本没用的，所以mac/linux 下会把 -i 后面跟着的 U 当做目标，然后后面所指定的 域名/IP 就不被识别了。。

**Comment by ttttmr** [comment]
@yu4hao4 @fa1c0n1 请认真看readme或使用-h参数查看如何使用，已经整合了目标输入方式
