### ISSUE TITLE
无法扫描出.phps的扩展名

### ISSUE THREAD

**Issue by raddyfiy** [H4ckForJob/dirmap#28]
环境:win10+py3
目标：攻防世界里的一道例题，web进阶区“php2”
执行代码:  py dirmap.py -i http://111.198.29.45:42890/ -lcf
问题：网站里有个index.phps，将这条添加到字典dict_mode_dict后用dirmap扫描无法扫出来，尝试用御剑可以。正常访问的状态码是200，但dirmap就是扫不出来，不清楚原理是什么。

**Comment by ttttmr** [comment]
使用默认配置，在dict_mode_dict.txt中追加index.phps，经过测试是可以扫出来的，是不是配置错了
![image](https://user-images.githubusercontent.com/32825326/61542380-08ad1580-aa74-11e9-911e-5ca8d17098df.png)

**Comment by xrry** [comment]
同样我也是这题扫不出来，所以来提issue了哈哈哈
![image](https://user-images.githubusercontent.com/24238515/61930557-b22e6280-afb0-11e9-8100-1a654d5b6e66.png)

**Comment by handbye** [comment]
我填了加字典也没扫出来
