### ISSUE TITLE
单字典扫描大量域名误报率有点多

### ISSUE THREAD

**Issue by B0luo** [H4ckForJob/dirmap#3]
自行设置单字典扫描，默认配置下，设置200 ok状态码。出现的结果大多是404之类的

**Comment by H4ckForJob** [comment]
@B0luo 你好，默认配置下，`conf.custom_404_page`这个配置为空，所以导致误报“返回状态码为200的404页面”

对于单个域名的解决方案：

自定义设置`conf.custom_404_page`配置

```txt
#自定义匹配404页面正则，例子：conf.custom_404_page = "fake 404"，其中fake 404是你的待测网站“返回状态码为200的404页面”
conf.custom_404_page = ""
```

写到这里，突然发现，你指的是多个域名。

emmm，目前只支持单个域名自定义匹配404页面。

对于扫描多个域名误报的问题，会尽快解决的，欢迎关注项目动态。

**Comment by B0luo** [comment]
> @ B0luo你好，默认配置下，`conf.custom_404_page`这个配置为空，所以导致误报“返回状态码为200的404页面”
> 
> 对于单个域名的解决方案：
> 
> 定义自设置`conf.custom_404_page`配置
> 
> ```
> #自定义匹配404页面正则，例子：conf.custom_404_page = "fake 404"，其中fake 404是你的待测网站“返回状态码为200的404页面”
> conf.custom_404_page = ""
> ```
> 
> 写到这里，突然发现，你指的是多个域名。
> 
> emmm，目前只支持单个域名自定义匹配404页面。
> 
> 对于扫描多个域名误报的问题，会尽快解决的，欢迎关注项目动态。

谢谢回复，再次感谢作者！

**Comment by H4ckForJob** [comment]
@B0luo 移植了cansina的自动识别404页面功能，修复多个域名误报的问题
