### ISSUE TITLE
关于bruter.py的bar.log.start()出错

### ISSUE THREAD

**Issue by wizardjk** [H4ckForJob/dirmap#33]
Traceback (most recent call last):
  File "D:\CTF\Web\dirmap-master\lib\controller\engine.py", line 44, in scan
    bruter(target)
  File "D:\CTF\Web\dirmap-master\lib\controller\bruter.py", line 592, in bruter
    bar.log.start(tasks.task_length)
TypeError: start() takes 1 positional argument but 2 were given

**Comment by ttttmr** [comment]
使用的命令参数是什么

**Comment by lonehand** [comment]
我也是同样的报错，命令是python3.6 dirmap.py -i https://realestate-fund.pingan.com.cn -lcf

**Comment by H4ckForJob** [comment]
@wizardjk @lonehand 首先，请git clone最新版本：）

关于bruter.py的bar.log.start()出错。解决方案：请安装progressbar2。卸载progressbar。防止导入同名模块。感谢某位表哥提醒。

执行命令：
```
python3 -m pip uninstall progressbar
python3 -m pip install progressbar2
```
