### ISSUE TITLE
如果可以，README字符编码建议设为UFT8

### ISSUE THREAD

**Issue by jslyrd** [H4ckForJob/dirmap#35]
实际使用时配置conf懒得看英文，less README.md 发现竟然不是unicode。当然只是建议。

**Comment by ttttmr** [comment]
是UTF-8编码的

**Comment by jslyrd** [comment]
非常抱歉提之前没有进行其他验证。原因是在Dokcer中使用，里头的vim没有设置编码，而less竟然将文件识别为binary。。。在本机上不会出现，打扰了。
