### ISSUE TITLE
目录遍历的情况没扫描出来

### ISSUE THREAD

**Issue by m01e-40x** [H4ckForJob/dirmap#41]
vendor目录是存在目录遍历的，字典里添加了 vendor，但扫描的时候没扫出来
![image](https://user-images.githubusercontent.com/11158624/66716913-d6f2e300-ee05-11e9-9a17-b1cb98571be2.png)
![image](https://user-images.githubusercontent.com/11158624/66716921-e96d1c80-ee05-11e9-9e8d-b02f2bb398a2.png)

**Comment by H4ckForJob** [comment]
@fa1c0n1 hello，请问扫描执行的命令可以提供一下吗？

**Comment by ttttmr** [comment]
怀疑是扫根目录，爆破到后没有爬，而且递归爬虫又没做就扫不出来 = =
