### ISSUE TITLE
dirmap单个目标找不到保存的结果

### ISSUE THREAD

**Issue by ANT-Yang** [H4ckForJob/dirmap#6]
您好，大佬，我执行完这个栗子的命令在output这个文件夹找不到保存的结果，请问可以在哪里自定义保存文件的路径吗（dirmap.py -iU https://target.com -lcf）
![图片](https://user-images.githubusercontent.com/22095675/56948085-a5d96b80-6b61-11e9-90b1-3a3ebca9a74d.png)

**Comment by H4ckForJob** [comment]
@ANT-Yang 因为未扫描到目录或文件，没有需要保存的结果，如果要测试的话，执行：

```shell
python3 dirmap.py -iU http://testphp.vulnweb.com -lcf
```
