### ISSUE TITLE
Fuzz模式不能使用吗？

### ISSUE THREAD

**Issue by komomon** [H4ckForJob/dirmap#61]
#Fuzz mode:Close :0;single dict:1;multiple dict:2
conf.fuzz_mode = 2  开启为1或2 使用dirmap报错
![image](https://user-images.githubusercontent.com/52700174/97840794-9c652c80-1d1f-11eb-96f1-3cbb74067a74.png)
麻烦看一下是不是程序有问题呢

**Comment by H4ckForJob** [comment]
该问题解决方案参考 #67
