### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableSet'

### ISSUE THREAD

**Issue by zz2846** [H4ckForJob/dirmap#70]
Traceback (most recent call last):
  File "/xxx/dirmap/dirmap.py", line 19, in <module>
    from lib.core.option import initoptions
  File "/xxx/dirmap/lib/core/option.py", line 21, in <module>
    from thirdlib.IPy.IPy import IP
  File "/xxx/dirmap/thirdlib/IPy/IPy.py", line 1020, in <module>
    class IPSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

**Comment by Xiao-Chen-Whoami** [comment]
这是python版本问题,用python3.10.1 我也是这个报错 折腾半天。。。。。结果换个python3.8.7就好了  ,应该是python3.10.X 就会这样

**Comment by lal0ne** [comment]
修改 `dirmap\thirdlib\IPy\IPy.py`
```py
# 第1020行
class IPSet(collections.MutableSet):
# 修改为
class IPSet(collections.abc.MutableSet):
```
