### ISSUE TITLE
use `conf.file_extension` problem

### ISSUE THREAD

**Issue by ppuuoo** [H4ckForJob/dirmap#75]
When blasting some stations, for example, the rfu directory can be accessed, but direct blasting cannot be blasted out, because when visiting this station, you must add / to rfu/ after the rfu. In this case, normal results can appear. I hope the author changes some , this little problem
<img width="304" alt="Snipaste_2022-06-05_20-35-14" src="https://user-images.githubusercontent.com/28812583/172050813-3b04bfa8-00b8-4358-a5e7-97ff978c0e49.png">

<img width="565" alt="Snipaste_2022-06-05_20-33-44" src="https://user-images.githubusercontent.com/28812583/172050817-67310838-4a17-4d73-aa80-a975925153ad.png">

.However, this directory cannot be scanned without adding /
<img width="304" alt="Snipaste_2022-06-05_20-35-14" src="https://user-images.githubusercontent.com/28812583/172050903-6f3f3c37-8f83-43ac-8048-39ed75381142.png">
<img width="637" alt="Snipaste_2022-06-05_20-40-21" src="https://user-images.githubusercontent.com/28812583/172050944-9177f328-ac9f-4d76-a5bc-2671ac438a61.png">
The blasting also can't be blasted out, it is suspected that the rfu is missing this rfu/
<img width="671" alt="Snipaste_2022-06-05_20-41-57" src="https://user-images.githubusercontent.com/28812583/172050986-46c90ef6-e134-4d58-a2f6-fe4f5cb94a50.png">
<img width="753" alt="Snipaste_2022-06-05_20-44-44" src="https://user-images.githubusercontent.com/28812583/172051087-46ced60f-0b3d-4291-8b8e-6f580d01f39e.png">

**Comment by H4ckForJob** [comment]
Try using this option to resolve forward slashes after suffix names
```
#Payload add file extension
conf.file_extension
```
