### ISSUE TITLE
如何使用fuzz_mode?

### ISSUE THREAD

**Issue by JarvisXyy** [H4ckForJob/dirmap#80]
设置conf.fuzz_mode = 1或2后，报错：Traceback (most recent call last):
  File "/Users/jarvis_xyy/dirmap/lib/controller/engine.py", line 44, in scan
    bruter(target)
  File "/Users/jarvis_xyy/dirmap/lib/controller/bruter.py", line 573, in bruter
    for payload in payloads.all_payloads:
TypeError: 'NoneType' object is not iterable

是payload队列为空吗，所以传入空值导致报错？

**Comment by H4ckForJob** [comment]
产生这个错误的原因是未指定fuzz标签。参考用法如下：`py -3 .\dirmap.py -i "http://localhost/web/{dir}" -lcf`

其中`{dir}`为fuzz标签，即fuzz字典的插入点
![image](https://github.com/H4ckForJob/dirmap/assets/39022267/40fe8f25-33dd-4c5b-9d64-ff6ef55e14ee)
