### ISSUE TITLE
proxy problem proxy

### ISSUE THREAD

**Issue by ppuuoo** [H4ckForJob/dirmap#86]
<img width="730" alt="image" src="https://github.com/H4ckForJob/dirmap/assets/28812583/9047c824-cf2a-4165-90e5-bd3e223cd593">

Sometimes I can't catch it using burpsuite, and sometimes I can catch it. I don't know why.
Does https require a certificate? For example, the browser must set up a certificate

**Comment by H4ckForJob** [comment]
try this config:`conf.proxy_server = {"http":"http://127.0.0.1:8080","https":"http://127.0.0.1:8080"}`

**Comment by ppuuoo** [comment]
It works indeed. Thank you very much.
